server:
  port: 8484
spring:
  application:
    name: credit-card-verify-service
  cloud:
    function:
      definition: verifyCreditCardApplication
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          replicationFactor: 1
      bindings:
        verifyCreditCardApplication-in-0:
          destination: CreditCardApplication
          group: credit-card
        verifyCreditCardApplication-out-0:
            destination: CreditCardVerification
            group: credit-card
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:credit-card-verify-application
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update